# Generated by Django 5.1.6 on 2025-10-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectT_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tirupathi_data_collection',
            old_name='title',
            new_name='name',
        ),
    ]
