# Generated by Django 5.2 on 2025-10-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectT_app', '0002_rename_title_tirupathi_data_collection_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tirupathi_data_collection',
            old_name='food_images',
            new_name='image',
        ),
    ]
