# Generated by Django 5.2 on 2025-10-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectT_app', '0003_rename_food_images_tirupathi_data_collection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirupathi_data_collection',
            name='category_name',
            field=models.CharField(default=20.54, max_length=50),
            preserve_default=False,
        ),
    ]
